#version 460 core

#define SCAN_ELEMENTS 512u

layout(local_size_x = 512) in;

layout(std430, binding = 6) buffer CellOffsetBuffer {
    uint cellOffsets[];
};

layout(std430, binding = 11) readonly buffer ScanBlockOffsetBuffer {
    uint scanBlockOffsets[];
};

uniform int cellCount;

void main()
{
    uint id = gl_GlobalInvocationID.x;
    if (id >= uint(cellCount)) return;

    uint blockIndex = id / SCAN_ELEMENTS;
    cellOffsets[id] += scanBlockOffsets[blockIndex];
}
